server:
   port: 9090


spring:
  application:
    name: emlakburada-gateway
  cloud:
    gateway:
      routes:
      - id: emlakburada
        uri: lb://emlakburada
        predicates:             
        - Path=/adverts/**, /users/**
      - id: emlakburada-banner
        uri: http://localhost:8081 
        predicates:
        - Path=/banners/**
        - Method=POST,GET 

  main:
    allow-bean-definition-overriding: true
    web-application-type: REACTIVE
#eureka:
#  client:
#    register-with-eureka: true
 #   serviceUrl:
  #    defaultZone: http://localhost:8761/eureka

logging:
  level:
    '[org.springframework.security]': TRACE
